### PR TITLE
#3: add eventsListener property to ExceptionHandlerBinder for ios

### LINKED ISSUE #3: Sometimes handeled errors are not displayed on iOS
It seems that there is a problem with ARC on iOS that kills the anonymous object of the listener:

```kotlin
actual class ExceptionHandlerBinderImpl<T : Any> actual constructor(
    private val errorPresenter: ErrorPresenter<T>,
    private val eventsDispatcher: EventsDispatcher<ErrorEventListener<T>>
) : ExceptionHandlerBinder {
    override fun bind(viewController: UIViewController) {
        eventsDispatcher.listener = object : ErrorEventListener<T> { // anonymous object
            override fun showError(throwable: Throwable, data: T) {
                errorPresenter.show(throwable, viewController, data)
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Tetraquark**
Closes #3

### CODE REVIEW

File: errors/src/iosMain/kotlin/dev/icerock/moko/errors/handler/ExceptionHandlerBinder.kt [hunk 1]
```diff
@@ -17,11 +17,18 @@ actual class ExceptionHandlerBinderImpl<T : Any> actual constructor(
...
+
+    private var eventsListener: ErrorEventListener<T>? = null
+
     override fun bind(viewController: UIViewController) {
-        eventsDispatcher.listener = object : ErrorEventListener<T> {
+        eventsListener = createEventsListener(viewController)
+        eventsDispatcher.listener = eventsListener
+    }
+
+    private fun createEventsListener(viewController: UIViewController) =
```
Comment (Alex009) [inline errors/src/iosMain/kotlin/dev/icerock/moko/errors/handler/ExceptionHandlerBinder.kt:28]: save `viewController` as WeakRefernece please

Comment (Tetraquark) [reply errors/src/iosMain/kotlin/dev/icerock/moko/errors/handler/ExceptionHandlerBinder.kt:29]: Fixed.
